#!/bin/sh

# PATH modification needed for http_post and oauth_sign
export PATH=$PATH:/usr/local/bin

toplevel_path=`git rev-parse --show-toplevel`
toplevel_dir=`basename "$toplevel_path"`

branch=`git rev-parse --abbrev-ref HEAD`
subject=`git log --pretty=format:%s -n1`
hashtags="🐾 #$toplevel_dir"
tweet=$hashtags' ['$branch']: "'$subject'"'

# truncate tweets that are longer than 140 characters
if [ ${#tweet} -gt 140 ]
    then
        tweet_trunc=$(echo $tweet | cut -c1-137)
        tweet=${tweet_trunc}...
fi

t update "$tweet"
